variables:
  DOCKER_REPOSITORY: registry.mender.io/cfengine/cfbuild
  DOCKERFILE: Dockerfile

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-build.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-deploy.yml'

stages:
  - build
  - publish
  - sync

publish:image:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(master|production)$/'

publish:image:mender:
  rules:
    - when: never

sync:image:
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
  variables:
    TARGET_MANIFEST_FILE: "kubernetes/build-cfengine-com/build-cfengine-com-deployment.yaml"

sync:image:staging:
  extends: sync:image
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  variables:
    TARGET_MANIFEST_FILE: "kubernetes/staging-build-cfengine-com/staging-build-cfengine-com-deployment.yaml"
