variables:
  DOCKER_REPOSITORY: registry.mender.io/cfengine/cfbuild
  DOCKERFILE: Dockerfile

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-build.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-deploy.yml'

stages:
  - build
  - publish
  - sync

build:docker:
  script:
    - echo "building ${CI_PROJECT_NAME} for ${DOCKER_BUILD_SERVICE_IMAGE}"
    - docker build
        --tag $DOCKER_BUILD_SERVICE_IMAGE
        --file ${DOCKER_DIR:-.}/${DOCKERFILE:-Dockerfile}
        --build-arg GIT_COMMIT_TAG="${DOCKER_PUBLISH_COMMIT_TAG}"
        --build-arg GITHUB_USERNAME_TOKEN
        ${DOCKER_DIR:-.}
    - docker save $DOCKER_BUILD_SERVICE_IMAGE > image.tar

publish:image:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(master|production)$/'

publish:image:mender:
  rules:
    - when: never

sync:image:
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
  variables:
    TARGET_MANIFEST_FILE: "kubernetes/build-cfengine-com/build-cfengine-com-deployment.yaml"

sync:image:staging:
  extends: sync:image
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  variables:
    TARGET_MANIFEST_FILE: "kubernetes/staging-build-cfengine-com/staging-build-cfengine-com-deployment.yaml"
