baseurl = "/"
languageCode = "en"
title = "CFEngine Build"
theme = "cfbs-theme"

# Number of posts per page
Paginate = 10
enableRobotsTXT = true
disqusShortname = 'cfengine-build'

[params.info]
homeTitle = "CFEngine Build" # Title for home page

[params.featured]
modules = ['promise-type-git', 'inventory-sudoers', 'autorun']

[taxonomies]
tag = "tags"
author = "author"
