baseurl = "/"
languageCode = "en"
title = "CFEngine Build"
theme = "cfbs-theme"

# Number of posts per page
Paginate = 10
enableRobotsTXT = true
disqusShortname = 'cfengine-build'

[params.info]
homeTitle = "CFEngine Build" # Title for home page

[params.suggested]
modules = ['promise-type-git.html', 'inventory-sudoers.html', 'autorun.html']

[taxonomies]
tag = "tags"
author = "author"
